name: Backend NestJS

on:
  push:
    paths:
      - 'backend-nestjs/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: npm install, run test
        working-directory: ./backend-nestjs
        run: |
         npm install
         npm test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./backend-nestjs/coverage/lcov.info # optional (default value)
