name: Backend NestJS

env:
  CI: true
  COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
  COVERALLS_GIT_BRANCH: "${{ github.ref }}"

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'backend-nestjs/**'
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - 'backend-nestjs/**'
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install
        working-directory: ./backend-nestjs
        run: npm install

      - name: Run Test
        working-directory: ./backend-nestjs
        run: npm test

      - name: Run Coveralls
        working-directory: ./backend-nestjs
        run: npm run coveralls
