name: Backend NestJS

on:
  push:
    paths:
      - 'backend-nestjs/**'
  pull-request:
    paths:
      - 'backend-nestjs/**'
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install
        working-directory: ./backend-nestjs
        run: npm install

      - name: Run Test
        working-directory: ./backend-nestjs
        run: npm test

      - name: Run Coveralls
        working-directory: ./backend-nestjs
        run: npm run coveralls
