name: Backend NestJS

on:
  push:
    paths:
      - 'backend-nestjs/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend-nestjs
      
      - name: Begin tests
        run: npm test
        working-directory: ./backend-nestjs
        env:
          CI: true
